### ISSUE TITLE
Container startup will fail if there is no internet access

### ISSUE THREAD

**Issue by DimmKirr** [peez80/docker-hivemq#3]
Great work!

Should this be rather baked in into a container (via `RUN`)?

https://github.com/peez80/docker-hivemq/blob/31136bd8de1b56fcd2ad14a866518ddcf4aac10e/docker-install-scripts/install_hivemq.sh#L11

**Comment by peez80** [comment]
Thanks ;) I'm not sure if I get your point. The line you mentioned is not executed during container runtime. It's only executed upon image build, which usually happens on docker hub or a developer machine.

See the Dockerfile for that:
https://github.com/peez80/docker-hivemq/blob/31136bd8de1b56fcd2ad14a866518ddcf4aac10e/Dockerfile#L9

It's common practice to download binaries during build time. If you're behind a proxy, you could use `--build-arg http_proxy --build-arg https_proxy` then your host proxy settings are used during the build.

Is that what you meant?

**Comment by DimmKirr** [comment]
I apologize, I didn't realize this is actually called during the build time.
Usually all commands are packed into a RUN layer (like in this [nginx](https://github.com/nginxinc/docker-nginx/blob/4f5bae5928baee89433ecb20a50283546f217dfa/mainline/alpine/Dockerfile) container), but you run a script, also i got a little bit tired that day, so I got confused. Great work, again!

**Comment by peez80** [comment]
Yeah I use that pattern usually if a image build needs many shell lines in order to keep the Dockerfile readable and to get IDE Code Inspection for the .sh files 😄
